remote_theme: WildCodeSchool/workshops-jekyll-theme

titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

style: dev
title: Deploy 02 - React Frontend
description: "How to deploy react sites developped with Harmonia hosted on Vercel"
show_clone: false
show_toc: true
lang: en